# Generated by Django 3.1.7 on 2021-05-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='prod_name',
            new_name='product',
        ),
    ]
