# Generated by Django 3.1.7 on 2021-05-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_editprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editprofile',
        ),
    ]
