# Generated by Django 3.1.7 on 2021-05-31 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210530_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editprofile',
        ),
    ]
