# Generated by Django 3.1.7 on 2021-05-31 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210531_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
